// <auto-generated />
using System;
using KnightsOfTheFallenCrown.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KnightsOfTheFallenCrown.Data.Migrations
{
    [DbContext(typeof(KnightsOfTheFallenCrownContext))]
    [Migration("20250407070040_Migger6")]
    partial class Migger6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KnightsOfTheFallenCrown.Core.Domain.FileToDatabase", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("KnightID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.ToTable("FilesToDatabase");
                });

            modelBuilder.Entity("KnightsOfTheFallenCrown.Core.Domain.Knight", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("KnightDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("KnightHasDied")
                        .HasColumnType("datetime2");

                    b.Property<int>("KnightHealth")
                        .HasColumnType("int");

                    b.Property<int>("KnightLevel")
                        .HasColumnType("int");

                    b.Property<string>("KnightName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KnightPerk")
                        .HasColumnType("int");

                    b.Property<int>("KnightStatus")
                        .HasColumnType("int");

                    b.Property<int>("KnightType")
                        .HasColumnType("int");

                    b.Property<DateTime>("KnightWasBorn")
                        .HasColumnType("datetime2");

                    b.Property<int>("KnightXP")
                        .HasColumnType("int");

                    b.Property<int>("KnightXPNextLevel")
                        .HasColumnType("int");

                    b.Property<string>("PrimaryAttackName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrimaryAttackPower")
                        .HasColumnType("int");

                    b.Property<string>("SecondaryAttackName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SecondaryAttackPower")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Knights");
                });
#pragma warning restore 612, 618
        }
    }
}
